// Renders src/icon.js (SVG) to PNG sizes and writes src/icon-data.js (base64), so the worker can serve
// icon.png / favicon.png / favicon.ico without a runtime rasterizer. macOS only (uses qlmanage).
// Run: npm run build:icons
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ICON_SVG } from '../src/icon.js';

const dir = mkdtempSync(join(tmpdir(), 'ohny-icon-'));
writeFileSync(join(dir, 'icon.svg'), ICON_SVG);
const png = (size) => {
  execFileSync('qlmanage', ['-t', '-s', String(size), '-o', dir, join(dir, 'icon.svg')], { stdio: 'ignore' });
  return readFileSync(join(dir, 'icon.svg.png'));
};
const p512 = png(512);
const p256 = png(256);
const p48 = png(48);

// ICO container holding PNG images (supported by all current browsers).
function ico(images) {
  const head = Buffer.alloc(6 + 16 * images.length);
  head.writeUInt16LE(1, 2); head.writeUInt16LE(images.length, 4);
  let offset = head.length;
  images.forEach(({ size, data }, i) => {
    const o = 6 + 16 * i;
    head[o] = size === 256 ? 0 : size; head[o + 1] = size === 256 ? 0 : size;
    head.writeUInt16LE(1, o + 4); head.writeUInt16LE(32, o + 6);
    head.writeUInt32LE(data.length, o + 8); head.writeUInt32LE(offset, o + 12);
    offset += data.length;
  });
  return Buffer.concat([head, ...images.map((i) => i.data)]);
}

const b64 = (b) => b.toString('base64');
writeFileSync(new URL('../src/icon-data.js', import.meta.url),
  `// Generated by scripts/build-icons.mjs from src/icon.js. Do not edit.\n` +
  `export const ICON_PNG_512 = '${b64(p512)}';\nexport const ICON_PNG_48 = '${b64(p48)}';\n` +
  `export const FAVICON_ICO = '${b64(ico([{ size: 48, data: p48 }, { size: 256, data: p256 }]))}';\n`);
console.log('wrote src/icon-data.js');
